import { StyleSheet } from 'react-native';

import { STREAMBOX_COLORS } from '../../constants/theme';

export const profileScreenStyles = StyleSheet.create({
  screen: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 16 },
  contentCompact: { paddingTop: 10, paddingBottom: 8 },
  header: { gap: 3 },
  eyebrow: {
    color: STREAMBOX_COLORS.accent,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },
  title: { fontSize: 34, fontWeight: '800', letterSpacing: -1.1, lineHeight: 40 },
  secondaryDark: { color: STREAMBOX_COLORS.descriptionDark },
  secondaryLight: { color: STREAMBOX_COLORS.descriptionLight },
  textDark: { color: STREAMBOX_COLORS.white },
  textLight: { color: '#17151F' },
  stats: { flexDirection: 'row', gap: 8, marginTop: 18 },
  statsCompact: { marginTop: 10 },
  progressStat: { marginTop: 8, height: 102 },
  progressStatCompact: { marginTop: 6, height: 76 },
  stat: {
    flex: 1,
    minHeight: 102,
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    justifyContent: 'space-between',
  },
  statCompact: { minHeight: 76, padding: 9 },
  surfaceDark: {
    backgroundColor: STREAMBOX_COLORS.cardDark,
    borderColor: STREAMBOX_COLORS.cardBorderDark,
  },
  surfaceLight: {
    backgroundColor: STREAMBOX_COLORS.white,
    borderColor: STREAMBOX_COLORS.cardBorderLight,
  },
  statCount: {
    color: STREAMBOX_COLORS.accent,
    fontSize: 32,
    lineHeight: 36,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  statCountCompact: { fontSize: 27, lineHeight: 30 },
  statLabel: { fontSize: 12, lineHeight: 15, fontWeight: '600' },
  statLabelCompact: { fontSize: 11, lineHeight: 13 },
  emptyState: { marginTop: 14, padding: 13, borderRadius: 16, gap: 4 },
  emptyStateCompact: { marginTop: 9, padding: 10 },
  emptyDark: { backgroundColor: STREAMBOX_COLORS.glowDark },
  emptyLight: { backgroundColor: STREAMBOX_COLORS.glowLight },
  emptyTitle: { fontSize: 16, fontWeight: '800' },
  emptyDescription: { fontSize: 14, lineHeight: 20 },
  sectionTitle: { fontSize: 18, fontWeight: '800', marginTop: 20, marginBottom: 10 },
  sectionTitleCompact: { marginTop: 10, marginBottom: 7 },
  links: { borderRadius: 20, borderWidth: 1, overflow: 'hidden' },
  link: {
    minHeight: 69,
    paddingHorizontal: 16,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  linkCompact: { minHeight: 50, paddingVertical: 8 },
  linkPressed: { opacity: 0.62 },
  linkContent: { flex: 1, gap: 5 },
  linkTitle: { fontSize: 16, fontWeight: '700' },
  linkDescription: { fontSize: 13, lineHeight: 18 },
  chevron: { color: STREAMBOX_COLORS.accent, fontSize: 28, lineHeight: 28 },
  divider: { borderTopWidth: StyleSheet.hairlineWidth, marginLeft: 18 },
  dividerDark: { borderTopColor: STREAMBOX_COLORS.cardBorderDark },
  dividerLight: { borderTopColor: STREAMBOX_COLORS.cardBorderLight },
});
